- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    instance_name: "{{ ec2_instance_name }}"
    instance_type: "{{ ec2_instance_type }}"
    image: ami-0d2da56e47a445b08
    security_group: demo-server-sg
    region: ap-southeast-3
    count: 1

  tasks:
    - name: Create a security group
      boto3:
        region: "{{ region }}"
        service: ec2
        api_call: create_security_group
        security_group_name: "{{ security_group }}"
        description: Security Group for demo server
        ingress_rules:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            IpRanges:
              - CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            IpRanges:
              - CidrIp: 0.0.0.0/0
        egress_rules:
          - IpProtocol: all
            IpRanges:
              - CidrIp: 0.0.0.0/0
      register: basic_firewall

    - name: Launch the new EC2 Instance
      boto3:
        region: "{{ region }}"
        service: ec2
        api_call: run_instances
        image_id: "{{ image }}"
        instance_type: "{{ instance_type }}"
        min_count: "{{ count }}"
        max_count: "{{ count }}"
        security_group_ids:
          - "{{ basic_firewall.group_id }}"
      register: ec2

    - name: Add Tagging to EC2 instance
      boto3:
        region: "{{ region }}"
        service: ec2
        api_call: create_tags
        resources: "{{ ec2.instances | map(attribute='id') | list }}"
        tags:
          - Key: Name
            Value: "{{ instance_name }}"
